---

- hosts: localhost
  gather_facts: false

  roles:

    - role: admission_token
      tags:
        - token

  tasks:

    - debug:
        var: admission_token
      tags:
        - token

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"

  become: true

  roles:

    - role: kubeadm_install
      tags:
        - repo
        - master
        - nodes          

  tasks:

    # Implements Step 2 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - name: Initialize master
      command: kubeadm init --token {{ hostvars.localhost.admission_token }} --use-kubernetes-version v1.5.4
      args:
        creates: /etc/kubernetes/pki
      register: master_init
      ignore_errors: true
      tags:
        - master
        - init

    - debug:
        var: master_init.stdout_lines

      # Not 100% sure that the creates clause is correct

- hosts: "{{ hostvars.localhost.groups.nodes | join(',') }}"

  become: true

  roles:

    - role: kubeadm_install
      tags:
        - repo
        - master
        - nodes    

  tasks:

    # Implements Step 3 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - set_fact:
        master_ip_address: '{{ master_ip_address_configured }}'
      when: master_ip_address_configured is defined

    - set_fact:
        master_ip_address: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}"
      when: master_ip_address_configured is not defined

    - name: Join nodes to cluster
      command: kubeadm join --token {{ hostvars.localhost.admission_token }} {{  master_ip_address }}
      args:
        creates: /etc/kubernetes/kubelet.conf
      register: node_join
      ignore_errors: true
      tags:
        - nodes
        - join

    - debug:
        var: node_join.stdout_lines

      # Not 100% sure that the creates clause is correct

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"

  become: true

  tasks:

    # Implements Step 4 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - name: Download contiv installer
      command: "{{ item }}"
      with_items:
        - curl -L -O https://github.com/contiv/install/releases/download/{{ contiv_ver }}/contiv-{{ contiv_ver }}.tgz 
        - tar zxf contiv-{{ contiv_ver }}.tgz
      register: contiv_download
      tags:
        - master

    - debug:
        var: contiv_download.results

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"

  become: true

  tasks:

    # Implements Step 4 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - name: Install contiv installer
      command: "{{ item }}"
      args: 
        chdir: "/root/contiv-{{ contiv_ver }}"
      with_items:
        - ./install/k8s/install.sh -n {{  master_ip_address }}
      register: pod_network
      tags:
        - master

    - debug:
        var: pod_network.results

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"

  become: true

  tasks:

    # Implements Step 4 of http://kubernetes.io/docs/getting-started-guides/kubeadm/
    - wait_for:
        port: 9999
        delay: 10

    - name: Create Contiv default-net
      command: netctl net create --subnet=10.96.0.0/12 default-net 
      register: create_network
      tags:
        - master

    - debug:
        var: create_network.stdout_lines
