- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"
  become: true
  tasks:
    # setup Kubernetes Web ui
    - name: setup Kubernetes Web ui
      command: "{{ item }}"
      with_items:
        - nohup kubectl proxy --address=0.0.0.0 --port=8001 --accept-hosts=^*$ &
        - curl -L -O  https://raw.githubusercontent.com/iceworld/ansible/master/kubernetes-dashboard.yaml
        - kubectl create -f ./kubernetes-dashboard.yaml
      register: kube_dashboard
      tags:
        - master
   
    - debug:
        var: kube_dashboard.results
